name: Test examples

on:
  push:
    branches: [main]

jobs:
  test-examples:
    runs-on: [ubuntu-latest]
    steps:
      - name: Install ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build
      
      - uses: actions/checkout@v4

      - name: CMake configure
        run: CXX=g++-14 cmake -G Ninja -B build -S .

      - name: CMake build
        run: cmake --build build

      - name: CTest
        run: ctest --output-on-failure
        working-directory: ./build
